---
abstract: 'Use Log::Any to handle logging from your Plack app'
author:
  - 'Michael Alan Dorman <mdorman@ironicdesign.com>'
build_requires:
  HTTP::Request::Common: 0
  Log::Any::Test: 0
  Plack::Test: 0
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-LogAny
requires:
  Log::Any: 0
  Plack::Middleware: 0
  Plack::Util::Accessor: 0
  parent: 0
  strict: 0
  warnings: 0
version: 0.001
